apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-two-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-two
  template:
    metadata:
      labels:
        app: consumer-two
    spec:
      containers:
        - name: consumer-two
          image: raorajath/python-consumer-two:latest
          ports:
            - containerPort: 5000
---
